apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: expressjs-template
  title: Express.js Template
  description: Creates a an Expressjs app for the StageCentral Workshop
spec:
  owner: user:guest
  type: app
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5 
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          description: Repo
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
               - github.com
  steps:
    - id: Log
      name: Log
      action: debug:log
      input: 
        message: "The name is ${{ parameters.name }}"  
